### ISSUE TITLE
Readme need to change "local" to Dayton

### ISSUE THREAD

**Issue by ejboettcher** [GemCityTECH/gemcity.tech#3]
The readme file should state that this is for Dayton's tech community.

Our mission is to grow Dayton's tech community....

vs

Out mission is to grow the local tech community.

**Comment by AllenMay** [comment]
Thanks for point this out.
The text has been updated to:
_GemCity TECH’s mission is to grow the Dayton industry and the Gem City community by providing a centralized destination for technical training, workshops and providing a forum for collaborating._
